let vatly ;
let hoahoc ;
let sinhhoc ;
vatly = parseInt(prompt('vatly'));
hoahoc = parseInt(prompt('hoahoc'));
sinhhoc = parseInt(prompt('sinhhoc'));
let trungbinhcong = (vatly + hoahoc + sinhhoc) / 3;
document.write("trung binh cong= "+ trungbinhcong);
let diemtong = vatly + hoahoc + sinhhoc;
document.write("diem tong= " + diemtong);
